#ifndef __SPRITES_H__
#define __SPRITES_H__

typedef enum SpriteType {
    // Buildings sprites
    SPRITE_CONSTRUCTION_CENTER = 0,
    SPRITE_WIND_TRAPS = 1,
    SPRITE_REFINERY = 2,
    SPRITE_ATREIDES_BARRACKS = 3,
    SPRITE_HARKUNNAN_BARRACKS = 4,
    SPRITE_ORDOS_BARRACKS = 5,
    SPRITE_LIGHT_FACTORY = 6,
    SPRITE_HEAVY_FACTORY = 7,
    SPRITE_SILO = 8,

    // Vehicles
    SPRITE_TRIKE = 10,
    SPRITE_HARVESTER = 11,
    SPRITE_RAIDER = 12,
    SPRITE_TANK = 13,

    // Units
    SPRITE_LIGHT_INFANTRY = 14,
    SPRITE_HEAVY_INFANTRY = 15,

    // Others
    SPRITE_ESPECIA = 16
} Sprites;

#define MAX_MOTION 4

typedef enum Direction {
    SPRITE_UP = 0,
    SPRITE_UP_RIGHT = 1,
    SPRITE_RIGHT = 2,
    SPRITE_DOWN_RIGHT = 3,
    SPRITE_DOWN = 4,
    SPRITE_DOWN_LEFT = 5,
    SPRITE_LEFT = 6,
    SPRITE_UP_LEFT = 7
} Direction;

#define DEFAULT_SPRITE_DIRECTION SPRITE_DOWN
#define DEFAULT_SPRITE_MOTION 0

#endif //__SPRITES_H__
